# The file here is a symlink to the `./builders.txt` located here, and using
# ~/.config/systemd/user/NetworkManager-monitor-ssh-available.service we make
# it available and unavailable according to the network state.
builders = @/home/doron/.local/share/nix/builders.txt
