experimental-features = nix-command flakes
substituters = https://cache.nixos.org https://thefloweringash-armv7.cachix.org https://r-doronbehar.cachix.org https://arm.cachix.org https://cache.nixos.org/ https://r-burns.cachix.org
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= r-doronbehar.cachix.org-1:oQAdHODfc9Nqqh9h1QYTOdrVxZC6c+rYP8qnBZ29STk=
